title: Tan Thinh Ngo - A Personal Tech Blog
logo: 'logo.png' # Add logo.
text_banner: 'text_banner.png' # Add banner
description: Passionate programmer.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Tan Thinh Ngo
  image: '/assets/img/myself.jpg'
  job: Full Stack Software Developer
  bio: As a software developer, I'm passionate about learning everything related to software development and technologies. I also seek opportunities to build high-quality applications and provide solutions for businesses.
  email: ngotanthinh92@gmail.com


# Contact links
contact:
  - name: Linkedin
    link: https://www.linkedin.com/in/tanthinhngo/
  - name: Facebook
    link: https://www.facebook.com/tanthinh0292/
  - name: Instagram
    link: https://www.instagram.com/ngotanthinh92/
  - name: Twitter
    link: https://twitter.com/TanThinh


# Comment Section (Disqus)
disqus-identifier: tan # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
permalink: pretty
paginate: 8

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-paginate