# Site settings
email: ngotanthinh92@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Titango's blog
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Thinh name
profile_img: /assets/image/profile/profile.png
profile: My name is <b>Ngo Tan Thinh</b>. I was born in 1992, Ho Chi Minh city, South of Vietnam.I have more than one-year work experience in web development and I'm now digging to be a full-stack developer. You can find my info and contact below.
social:
  github: https://github.com/titango
  facebook: https://www.facebook.com/tanthinh0292
  skype: skype:thinh.tan92?userinfo

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
